### ISSUE TITLE
Use testdata for personal identity number

### ISSUE THREAD

**Issue by PeterOrneholm** [kolplattformen/embedded-api#51]
> ### Fake user
> 
> Login with personal number `12121212121212`, `201212121212` or `1212121212` and
> api will be put into fake mode.
> Static data will be returned and no calls to backend will be made.

For testing purposes, thsese numbers are used:
- `12121212121212` (https://swedish.identityinfo.net/personalidentitynumber/validate?number=12121212121212)
- `201212121212` (https://swedish.identityinfo.net/personalidentitynumber/validate?number=201212121212)
- `1212121212` (https://swedish.identityinfo.net/personalidentitynumber/validate?number=1212121212)

While the first one is not a valid number (to long), the other two ones are. Because of this, there might pe users who cannot log in (5 years until they can have BankID, but still..) and we might use someone's real identity in our fake data.

For this exact purpose, Swedish the tax authorities (Skatteverket) have issued a list of reserved personal identity numbers (personnummer) we could use. They will be valid ones - but guaranteed not to be used by any real person.

I'd suggest we replace them with these numbers. Changing to people ~35 years old, as I (guess?) it is the parents that login.

- `198611239883` (https://swedish.identityinfo.net/personalidentitynumber/validate?number=198611239883)
- `8501139995` (https://swedish.identityinfo.net/personalidentitynumber/validate?number=8501139995)
- `8412099296` (https://swedish.identityinfo.net/personalidentitynumber/validate?number=8412099296)

The source of this dataset can be found here:
- https://www.skatteverket.se/omoss/utvecklingavdigitalatjanster/oppnadatapsidata.4.361dc8c15312eff6fd1736c.html
- https://skatteverket.entryscape.net/catalog/9/datasets/147

*Disclaimer: * I'm the author of the site https://swedish.identityinfo.net/ reffered to abvove. It builds on the publically available datasets from Skatteverket.

**Comment by JohanObrink** [comment]
Thant you! That is a very good point. The only problem is that we can't instruct the user so login with fake pnr 198611239883 since it's too hard to memorize.

I think the solution should be to add a fake-option on the login screen which fills in the fake pnr.

As soon as we figure out the updated login-screen, I'll implement this change.

**Comment by PeterOrneholm** [comment]
Very good point! The "easiest" number I could find is: `0101012383` but that is still hard.

A fake option on login screen sounds better!

**Comment by whyer** [comment]
Login as testuser implementet on login screen. Closing this.
